version: '3.9'
services:
  app:
    container_name: go_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=database123
      - POSTGRES_DB=postgres
      - DATABASE_HOST=postgresdb
      - DATABASE_PORT=5423
    tty: true
    build: .
    ports:
      - '4000:4000'
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - learning

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=helmetuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=motohelmet
    ports:
      - '5432:5432'
    volumes:
      - .:/app
    networks:
      - learning

networks:
  learning:
    driver: bridge